In [3]:
import pandas as pd

In [4]:
hifi_df = pd.read_csv('hifi_qc/hifi_qc_samples_output_table.csv')
hifi_qc = pd.concat([pd.read_csv(qc,sep='\t') for qc in hifi_df['hifi_qc_summary'].tolist()])
hifi_qc['sample_id'] = [sample.split('-')[0] for sample in hifi_qc['filename'].tolist()]
# hifi_qc['coverage'] = [bp/3.1 for bp in hifi_qc['total_Gbp'].tolist()]

In [5]:
hifi_qc.drop(columns=['all_kinetics_flag', 'keep_kinetics_flag', 'hifi_kinetics_tag', 'PP_PRIMROSE', 'fi_tag', 'ri_tag','fp_tag', 'rp_tag'],inplace=True)

In [8]:
hifi_qc.groupby('sample_id')['total_Gbp'].sum().div(3.1).reset_index(name='coverage')

   sample_id   coverage
0    HG00658  27.541935
1    HG01150  18.438710
2    HG01252  16.703226
3    HG01530  10.619355
4    HG01784  21.038710
5    HG01940  18.454839
6    HG01960  16.619355
7    HG01969  19.358065
8    HG02391  10.009677
9    HG02514  19.741935
10   HG02841  25.264516
11   HG02984  23.438710
12   HG03050  10.474194
13   HG03458  26.512903
14   HG03470  22.067742
15   HG03742  13.167742
16   NA18570  16.209677
17   NA19087  18.780645
18   NA19159   7.641935
19   NA19185   8.751613
20   NA19338  20.603226
21   NA19391  22.874194
22   NA19468  19.751613
23   NA20799  21.229032

In [ ]:
hifi_qc.to_csv('RU_Y3_topoff_sample_file_hifi_qc.csv',index=False)